spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: true

    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.0.100:3306/transaction_test
    username: transaction_test
    password: mhkkSsskDn7ctk5c